"""add composite index on requests status and request_class

Revision ID: 042e7d748137
Revises: 9b44db9035bc
Create Date: 2026-09-22 19:09:33.551264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042e7d748137'
down_revision: Union[str, Sequence[str], None] = '9b44db9035bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_requests_status_request_class', 'requests', ['status', 'request_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_status_request_class', table_name='requests')
    # ### end Alembic commands ###
