"""initial schema

Revision ID: 9b44db9035bc
Revises: 
Create Date: 2026-09-22 13:12:55.404736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b44db9035bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_display_name', sa.String(length=200), nullable=False),
    sa.Column('meeting_booking_url', sa.String(length=2000), nullable=True),
    sa.Column('meeting_booking_text', sa.Text(), nullable=True),
    sa.Column('quick_action_minutes', sa.Integer(), nullable=False),
    sa.Column('urgency_green_days', sa.Integer(), nullable=False),
    sa.Column('urgency_red_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_number', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('requester_name', sa.String(length=200), nullable=False),
    sa.Column('requester_email', sa.String(length=320), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('additional_context', sa.Text(), nullable=True),
    sa.Column('request_class', sa.Enum('quick', 'long', name='requestclass'), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'queued', 'in_progress', 'needs_information', 'done', 'declined', 'withdrawn', name='requeststatus'), nullable=False),
    sa.Column('previous_status', sa.Enum('submitted', 'queued', 'in_progress', 'needs_information', 'done', 'declined', 'withdrawn', name='requeststatus'), nullable=True),
    sa.Column('desired_completion_date', sa.Date(), nullable=True),
    sa.Column('desired_date_reason', sa.Text(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('previous_queue_position', sa.Integer(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('new_information_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_access_token'), 'requests', ['access_token'], unique=True)
    op.create_index(op.f('ix_requests_public_number'), 'requests', ['public_number'], unique=True)
    op.create_table('information_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('owner_question', sa.Text(), nullable=False),
    sa.Column('requester_response', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('submitted', 'accepted', 'info_requested', 'info_responded', 'started', 'returned_to_queue', 'completed', 'declined', 'withdrawn', 'moved_to_long', 'information_added', 'reordered', name='eventtype'), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_updates')
    op.drop_table('request_links')
    op.drop_table('request_events')
    op.drop_table('information_requests')
    op.drop_index(op.f('ix_requests_public_number'), table_name='requests')
    op.drop_index(op.f('ix_requests_access_token'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('request_counter')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
